# Generated by Django 5.2 on 2025-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GE', 'General'), ('BU', 'Business'), ('PO', 'Political'), ('SP', 'Sports'), ('SC', 'Science'), ('TE', 'Technology'), ('HE', 'Health'), ('AR', 'Art')], default='GE', max_length=2)),
            ],
        ),
    ]
